package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"

	"example.com/template/backend/internal/graphql/generated"
)

// SystemStatus is the resolver for the systemStatus field.
func (r *queryResolver) SystemStatus(ctx context.Context) (*generated.SystemStatus, error) {
	if r.System == nil {
		return nil, errors.New("system service is unavailable")
	}
	status := r.System.Status(ctx)
	return &generated.SystemStatus{DatabaseReady: status.DatabaseReady}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
